### PR TITLE
Make binary subtypes match spec

### PR DESCRIPTION
**Pull request by samwar**
Correcting the binary subtypes to match the bson binary subtype spec
found here: http://bsonspec.org/spec.html.

### CODE REVIEW

**Comment by samwar** [comment]
```
$ ./rebar eunit
==> bson-erlang (eunit)
Compiled src/bson_schema.erl
Compiled src/bson_binary.erl
Compiled test/bson_tests.erl
Compiled src/bson.erl
======================== EUnit ========================
module 'bson_schema'
module 'bson'
  module 'bson_tests'
    bson_tests: bson_test...[0.001 s] ok
    bson_tests: time_test...ok
    bson_tests: objectid_test...ok
    bson_tests: binary_test...ok
    bson_tests: put_document_test...ok
    bson_tests: bson_int_too_large_test...ok
    bson_tests: bad_bson_test...ok
    bson_tests: bson_document_test...ok
    bson_tests: str_test...ok
    bson_tests: utf8_test...ok
    bson_tests: maps_put_test...ok
    bson_tests: maps_get_test...ok
    bson_tests: maps_flattering_test...ok
    [done in 0.040 s]
  [done in 0.040 s]
module 'bson_binary'
=======================================================
  All 13 tests passed.
Cover analysis: /Users/samu6978/projects/temp/bson-erlang/.eunit/index.html

Code Coverage:
bson        : 87%
bson_binary : 98%
bson_schema :  0%

Total       : 76%
```

**Comment by samwar** [comment]
I checked that the `uuid` type wasn't used in https://github.com/comtihon/mongodb-erlang, and the use of this modified bson library following the spec passes all of our tests in our enterprise product.

**Comment by comtihon** [comment]
Thanks!

**Comment by samwar** [comment]
@comtihon Awesome! Now that you've merge this PR, any chance you can add a new release?

**Comment by comtihon** [comment]
`v0.2.3` was added

**Comment by samwar** [comment]
Awesome thanks!

**Pull request merged**
